[project]
name = "smugmug"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests-oauthlib>=2.0.0",
    "rich>=14.2.0",
    "typer>=0.21.1",
]
